language: android
# Use the Travis Container-Based Infrastructure
sudo: false

jdk:
  - oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-26.0.1
    - android-23
    - extra-android-m2repository

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"

before_script:
  - chmod +x gradlew

script:
  - ./gradlew build
